### ISSUE TITLE
About the content and style data.

### ISSUE THREAD

**Issue by ultraman-blazar** [irasin/Pytorch_Style_Swap#1]
If I want to transfer any image A (content) to image B (style) with
high quality, how much data should I prepare? Should I prepare lots of content data and single style image (just single style)? 
Thank you.

**Comment by irasin** [comment]
Hi, @Nisekoixmy 

If you just want to train a single style transfer model, you have no necessary to use style_swap because it is an Arbitrary Style Per Model method.

Just try the Single Style Per Model methods like Gatys et al.  or Johnson et al.
